server:
  host: "kvm-api.lab.vn.ua"
  node_id: "cab2e9b3-318e-43d4-96e9-c9511ac3b889"
  auth:
    login_url: "https://kvm-api.lab.vn.ua/api/v1/auth/login"
    username: "admin"
    password: "devpassword123!"
  video:
    proto: "webrtc"
    host: "kvm-api.lab.vn.ua"
    port: 443
    path: "/api/v1/nodes/${node_id}/signal/offer"
  hid:
    host: "pi4.lab.vn.ua"
    proto: "wss"
    port: 443
    path: "/ws/control"
